Remove binding for nonexistent SyntheticDataTransfer class
This was causing dart2js errors that looked like:

    Warning: 'gJ2' is used reflectively but not in MirrorsUsed. This will break minified code.
    14:38:58.512 react_with_react_dom_prod.js:100 Uncaught Error: NoSuchMethodError: method not found: 'gJ2'